[2020-09-26 09:00:28,235] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2020-09-24T00:00:00+00:00 [queued]>
[2020-09-26 09:00:28,244] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: example_bash_operator.run_after_loop 2020-09-24T00:00:00+00:00 [queued]>
[2020-09-26 09:00:28,244] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-09-26 09:00:28,245] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-09-26 09:00:28,245] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-09-26 09:00:28,251] {taskinstance.py:900} INFO - Executing <Task(BashOperator): run_after_loop> on 2020-09-24T00:00:00+00:00
[2020-09-26 09:00:28,253] {standard_task_runner.py:53} INFO - Started process 90152 to run task
[2020-09-26 09:00:28,306] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: example_bash_operator.run_after_loop 2020-09-24T00:00:00+00:00 [running]> 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2020-09-26 09:00:28,323] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/zt/cl_z4pfj4d5fs8dfnhz23whh0000gn/T
[2020-09-26 09:00:28,324] {bash_operator.py:105} INFO - Temporary script location: /var/folders/zt/cl_z4pfj4d5fs8dfnhz23whh0000gn/T/airflowtmp4fpem0dm/run_after_loopdpqlzewr
[2020-09-26 09:00:28,325] {bash_operator.py:115} INFO - Running command: echo 1
[2020-09-26 09:00:28,331] {bash_operator.py:122} INFO - Output:
[2020-09-26 09:00:28,334] {bash_operator.py:126} INFO - 1
[2020-09-26 09:00:28,334] {bash_operator.py:130} INFO - Command exited with return code 0
[2020-09-26 09:00:28,341] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=example_bash_operator, task_id=run_after_loop, execution_date=20200924T000000, start_date=20200926T160028, end_date=20200926T160028
[2020-09-26 09:00:38,230] {logging_mixin.py:112} INFO - [2020-09-26 09:00:38,229] {local_task_job.py:103} INFO - Task exited with return code 0
